name: "🚀 Feature Request"
description: Suggest a new feature or enhancement
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Description
      description: What feature would you like to see?
      placeholder: Support for string interpolation
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: Why would this feature be useful?

  - type: textarea
    attributes:
      label: Possible Implementation
      description: If you have ideas for how to implement it, describe them here.
